# Generated by Django 2.2.1 on 2019-06-15 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealIdeaName', models.CharField(max_length=250)),
                ('mealIdeaDescription', models.CharField(max_length=250)),
                ('mealIdeaCategory', models.CharField(choices=[('meat', 'Viande'), ('fish', 'Poisson'), ('vegetable', 'Légume'), ('starchy', 'Féculent'), ('dough', 'Pâte'), ('dessert', 'Dessert')], max_length=20)),
                ('mealIdeaSteps', models.TextField(max_length=5000)),
                ('mealIdeaImage', models.ImageField(upload_to='media')),
                ('mealIdeaLikes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('mealIdeaPublisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('diamanche', 'Dimanche')], max_length=20)),
                ('momentDay', models.CharField(choices=[('midi', 'Midi'), ('soir', 'Soir')], max_length=20)),
                ('typeMeal', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert')], max_length=20)),
                ('ideaDayUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mealId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keskon.MealIdea')),
            ],
        ),
    ]
